### ISSUE TITLE
Please add Diamond and Prosperity cost for ATM8

### ISSUE THREAD

**Issue by grayfallstown** [AnimatorOfSouls/Inferium-Calculator#1]

**Comment by SilencedGoose** [comment]
What do you mean by diamond/prosperity cost? For the infusion crystals?

**Comment by SilencedGoose** [comment]
If you do mean infusion crystals then I won't be adding that for now since this is something I made for use after you get the master infusion crystal. I might add it later, but for now you could try adding the "Just Enough Calculation" mod since it works client side.
